# Generated by Django 4.0.3 on 2022-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
